%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%% SCORE BASIC %%%%%%% 
x0 = 0.3; y0 = 0.3;
width = 8; height = 8;
x_min = 0; 
x_max = 5000*200;
y_min = -20;
y_max = 120;

episodes = (1:200) * 5000;

figure('Units','inches',...
'Position',[x0 y0 width height],...
'PaperPositionMode','auto');
set(gca,...
'Units','normalized',...
'YTick',y_min:20:y_max,...
'XTick',0:100000:x_max,...
'XTickLabelRotation',0,...
'Position',[.15 .2 .75 .7],...
'FontUnits','points',...
'FontWeight','normal',...
'FontSize',18,...
'FontName','Times')
hold on
chuck_i = 1:5:length(results_basic_score)-4;
results_chunk = [];
id = 1;
for i=chuck_i    
    results_chunk(id) = max(results_basic_score(i:i+4));
    id = id+1;
end

plot(episodes,results_chunk,'LineWidth',1)
hold on
axis([x_min x_max y_min y_max])
hold on

title('key-door easy task - test scores',...
    'FontUnits','points',...
'FontWeight','normal',...
'FontSize',24,...
'FontName','Times')
hold on

legend({'key=$(0,0)$ and door=$(1,1)$'},...
    'FontUnits','points',...
'interpreter','latex',...
'FontSize',24,...
'FontName','Times',...
'Location','best')
hold on

ylabel({'Total Scores'},...
'FontUnits','points',...
'interpreter','latex',...
'FontSize',24,...
'FontName','Times')
hold on

xlabel('Episodes',...
'FontUnits','points',...
'FontWeight','normal',...
'FontSize',24,...
'FontName','Times')
hold on

box on

hold off
print -depsc2 basic-scores.eps

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%% SCORES HARD %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
x0 = 0.3; y0 = 0.3;
width = 8; height = 8;

episodes = (1:200) * 5000;

figure('Units','inches',...
'Position',[x0 y0 width height],...
'PaperPositionMode','auto');

x_min = 0; 
x_max = 5000*200;
y_min = -20;
y_max = 120;

set(gca,...
'Units','normalized',...
'YTick',y_min:20:y_max,...
'XTick',0:100000:x_max,...
'XTickLabelRotation',0,...
'Position',[.15 .2 .75 .7],...
'FontUnits','points',...
'FontWeight','normal',...
'FontSize',18,...
'FontName','Times')
hold on
chuck_i = 1:5:length(results_hard_score)-4;
results_chunk = [];
id = 1;
for i=chuck_i    
    results_chunk(id) = max(results_hard_score(i:i+4));
    id = id+1;
end

plot(episodes,results_chunk,'LineWidth',1)
hold on


axis([x_min x_max y_min y_max])
hold on

title('key-door hard task - test scores',...
    'FontUnits','points',...
'FontWeight','normal',...
'FontSize',24,...
'FontName','Times')
hold on

legend({'key and door in random locations'},...
    'FontUnits','points',...
'interpreter','latex',...
'FontSize',24,...
'FontName','Times',...
'Location','best')
hold on

ylabel({'Total Scores'},...
'FontUnits','points',...
'interpreter','latex',...
'FontSize',24,...
'FontName','Times')
hold on

xlabel('Episodes',...
'FontUnits','points',...
'FontWeight','normal',...
'FontSize',24,...
'FontName','Times')
hold on

box on

print -depsc2 hard-scores.eps

hold off


%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%% SUCCESS HARD %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

x0 = 0.3; y0 = 0.3;
width = 8; height = 8;

x_min = 0; 
x_max = 5000*200;
y_min = 0;
y_max = 30;

episodes = (1:200) * 5000;

figure('Units','inches',...
'Position',[x0 y0 width height],...
'PaperPositionMode','auto');
set(gca,...
'Units','normalized',...
'YTick',y_min:5:y_max,...
'XTick',0:100000:x_max,...
'XTickLabelRotation',0,...
'Position',[.15 .2 .75 .7],...
'FontUnits','points',...
'FontWeight','normal',...
'FontSize',18,...
'FontName','Times')
hold on
chuck_i = 1:5:length(results_hard_success)-4;
results_chunk = [];
id = 1;
for i=chuck_i    
    results_chunk(id) = max(results_hard_success(i:i+4));
    id = id+1;
end

plot(episodes,100*results_chunk,'LineWidth',1)
hold on



axis([x_min x_max y_min y_max])
hold on

title('key-door hard task - success rate',...
    'FontUnits','points',...
'FontWeight','normal',...
'FontSize',24,...
'FontName','Times')
hold on

legend({'key and door in random locations'},...
    'FontUnits','points',...
'interpreter','latex',...
'FontSize',24,...
'FontName','Times',...
'Location','best')
hold on

ylabel({'Success $(\%)$'},...
'FontUnits','points',...
'interpreter','latex',...
'FontSize',24,...
'FontName','Times')
hold on

xlabel('Episodes',...
'FontUnits','points',...
'FontWeight','normal',...
'FontSize',24,...
'FontName','Times')
hold on

box on

print -depsc2 hard-success.eps

hold off


%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%% SUCCESS Basic %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

x0 = 0.3; y0 = 0.3;
width = 8; height = 8;

episodes = (1:200) * 5000;

x_min = 0; 
x_max = 5000*200;
y_min = 0;
y_max = 105;


figure('Units','inches',...
'Position',[x0 y0 width height],...
'PaperPositionMode','auto');
set(gca,...
'Units','normalized',...
'YTick',y_min:10:y_max,...
'XTick',0:100000:x_max,...
'XTickLabelRotation',0,...
'Position',[.15 .2 .75 .7],...
'FontUnits','points',...
'FontWeight','normal',...
'FontSize',18,...
'FontName','Times')
hold on
chuck_i = 1:5:length(results_basic_success)-4;
results_chunk = [];
id = 1;
for i=chuck_i    
    results_chunk(id) = max(results_basic_success(i:i+4));
    id = id+1;
end

plot(episodes,100*results_chunk/2,'LineWidth',1)
hold on


axis([x_min x_max y_min y_max])
hold on

title('key-door easy task - success rate',...
    'FontUnits','points',...
'FontWeight','normal',...
'FontSize',24,...
'FontName','Times')
hold on

legend({'key=(0,0) and door=(1,1)'},...
    'FontUnits','points',...
'interpreter','latex',...
'FontSize',24,...
'FontName','Times',...
'Location','best')
hold on

ylabel({'Success $(\%)$'},...
'FontUnits','points',...
'interpreter','latex',...
'FontSize',24,...
'FontName','Times')
hold on

xlabel('Episodes',...
'FontUnits','points',...
'FontWeight','normal',...
'FontSize',24,...
'FontName','Times')
hold on

box on

print -depsc2 basic-success.eps

hold off

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%% SCORE Medium %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%% 
x0 = 0.3; y0 = 0.3;
width = 8; height = 8;
x_min = 0; 
x_max = 5000*200;
y_min = -15;
y_max = 15;

episodes = (1:200) * 5000;

figure('Units','inches',...
'Position',[x0 y0 width height],...
'PaperPositionMode','auto');
set(gca,...
'Units','normalized',...
'YTick',-10:5:10,...
'XTick',0:100000:x_max,...
'XTickLabelRotation',0,...
'Position',[.15 .2 .75 .7],...
'FontUnits','points',...
'FontWeight','normal',...
'FontSize',18,...
'FontName','Times')
hold on
chuck_i = 1:5:length(results_medium_score)-4;
results_chunk = [];
id = 1;
for i=chuck_i    
    results_chunk(id) = max(results_medium_score(i:i+4));
    id = id+1;
end

plot(episodes,results_chunk,'LineWidth',1)
hold on


axis([x_min x_max y_min y_max])
hold on

title('Reaching to key task - test scores',...
    'FontUnits','points',...
'FontWeight','normal',...
'FontSize',24,...
'FontName','Times')
hold on

legend({'key in random location'},...
    'FontUnits','points',...
'interpreter','latex',...
'FontSize',24,...
'FontName','Times',...
'Location','best')
hold on

ylabel({'Total Scores'},...
'FontUnits','points',...
'interpreter','latex',...
'FontSize',24,...
'FontName','Times')
hold on

xlabel('Episodes',...
'FontUnits','points',...
'FontWeight','normal',...
'FontSize',24,...
'FontName','Times')
hold on

box on

hold off
print -depsc2 medium-scores.eps


%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%% SUCCESS Medium %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

x0 = 0.3; y0 = 0.3;
width = 8; height = 8;

x_min = 0; 
x_max = 5000*200;
y_min = 0;
y_max = 60;

episodes = (1:200) * 5000;

figure('Units','inches',...
'Position',[x0 y0 width height],...
'PaperPositionMode','auto');
set(gca,...
'Units','normalized',...
'YTick',y_min:10:y_max,...
'XTick',0:100000:x_max,...
'XTickLabelRotation',0,...
'Position',[.15 .2 .75 .7],...
'FontUnits','points',...
'FontWeight','normal',...
'FontSize',18,...
'FontName','Times')
hold on
chuck_i = 1:5:length(results_medium_success)-4;
results_chunk = [];
id = 1;
for i=chuck_i    
    results_chunk(id) = max(results_medium_success(i:i+4));
    id = id+1;
end

plot(episodes,100*results_chunk,'LineWidth',1)
hold on

axis([x_min x_max y_min y_max])
hold on

title('Reaching to key task - success rate',...
    'FontUnits','points',...
'FontWeight','normal',...
'FontSize',24,...
'FontName','Times')
hold on

legend({'key in random location'},...
    'FontUnits','points',...
'interpreter','latex',...
'FontSize',24,...
'FontName','Times',...
'Location','best')
hold on

ylabel({'Success $(\%)$'},...
'FontUnits','points',...
'interpreter','latex',...
'FontSize',24,...
'FontName','Times')
hold on

xlabel('Episodes',...
'FontUnits','points',...
'FontWeight','normal',...
'FontSize',24,...
'FontName','Times')
hold on

box on

print -depsc2 medium-success.eps

hold off

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%% SUCCESS EASY %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

x0 = 0.3; y0 = 0.3;
width = 8; height = 8;

x_min = 0; 
x_max = 5000*200;
y_min = 0;
y_max = 105;

episodes = (1:200) * 5000;

figure('Units','inches',...
'Position',[x0 y0 width height],...
'PaperPositionMode','auto');
set(gca,...
'Units','normalized',...
'YTick',y_min:10:y_max,...
'XTick',0:100000:x_max,...
'XTickLabelRotation',0,...
'Position',[.15 .2 .75 .7],...
'FontUnits','points',...
'FontWeight','normal',...
'FontSize',18,...
'FontName','Times')
hold on
chuck_i = 1:5:length(results_easy_success)-4;
results_chunk = [];
id = 1;
for i=chuck_i    
    results_chunk(id) = max(results_easy_success(i:i+4));
    id = id+1;
end

plot(episodes,100*results_chunk,'LineWidth',1)
hold on

axis([x_min x_max y_min y_max])
hold on

title('Reaching to key task - success rate',...
    'FontUnits','points',...
'FontWeight','normal',...
'FontSize',24,...
'FontName','Times')
hold on

legend({'key in neighborhood of initial state'},...
    'FontUnits','points',...
'interpreter','latex',...
'FontSize',24,...
'FontName','Times',...
'Location','best')
hold on

ylabel({'Success $(\%)$'},...
'FontUnits','points',...
'interpreter','latex',...
'FontSize',24,...
'FontName','Times')
hold on

xlabel('Episodes',...
'FontUnits','points',...
'FontWeight','normal',...
'FontSize',24,...
'FontName','Times')
hold on

box on

print -depsc2 easy-success.eps

hold off



